eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 8904
spring:
    application:
        name: service-zuul
zuul:
  routes:
    ribbo:
      path: /api-ribbon/**
      serviceId: ribbon-client
    feign:
      path: /api-feign/**
      serviceId: feign-client