server:
  port: 8040
  servlet:
    context-path: /ms-gateway-zuul

logging:
  level:
    root: info
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace

###actuator###
info:
  app:
    name: ${server.servlet.context-path}
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      taget: @java.version@
management:
  endpoints:
    web:
      exposure:
        include: ["*"]

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
spring:
  application:
    name: ms-gateway-zuul
zuul:
  routes:
    api-user-feign:
      path: /api-user-feign/**
      service-id: ms-feign-hystrix-consumer
    api-user-ribbon:
      path: /api-user-ribbon/**
      service-id: ms-ribbon-hystrix-consumer
