server:
  port: 8080
  servlet:
    context-path: /ms-provider
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
    username: sa
    password: 123456
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  application:
    name: ms-provider
logging:
  level:
    root: info
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace


###actuator###
info:
  app:
    name: ${server.servlet.context-path}
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      taget: @java.version@
management:
  endpoints:
    web:
      exposure:
        include: ["*"]
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    metadata-map:
      my-metadata: 自定义元数据
    ip-address: 127.0.0.1
