server:
  port: 8081
  servlet:
    context-path: /commons

spring:
    application:
        name: service-helloworld

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
          enabled: true
  instance:
      statusPageUrlPath: ${server.servlet.context-path}/health
      healthCheckUrlPath: ${server.servlet.context-path}/health