server:
  port: 8081
  servlet:
    context-path: /commons


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
          enabled: true
  instance:
      statusPageUrlPath: ${server.servletPath}/info
      healthCheckUrlPath: ${server.servletPath}/health