server:
  port: 8081
  servlet:
    context-path: /ms-consumer

logging:
  level:
    root: info
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace

