server:
  port: 8081
  servlet:
    context-path: /ms-consumer

logging:
  level:
    root: info
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace

###actuator###
info:
  app:
    name: ${server.servlet.context-path}
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      taget: @java.version@
management:
  endpoints:
    web:
      exposure:
        include: ["*"]

spring:
  application:
    name: ms-consumer
ms-provider:
  ribbon:
    listOfServers: localhost:8080,localhost:8088