drop table T_user if EXISTS ;
create table T_USER
(
  id bigint generated by default as IDENTITY ,
  username varchar(40),
  name varchar(20),
  age int(3),
  balance decimal(10,2),
  PRIMARY key(id)
);