server:
  servlet:
    context-path: /ms-turbine
  port: 8031
logging:
  level:
    root: info
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace

###actuator###
info:
  app:
    name: ${server.servlet.context-path}
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      taget: @java.version@
management:
  endpoints:
    web:
      exposure:
        include: ["*"]

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    metadata-map:
      my-metadata: 自定义元数据
    ip-address: 127.0.0.1
turbine:
  app-config: ms-ribbon-hystrix-consumer, ms-feign-hystrix-consumer
  aggregator:
    clusterConfig: ribbon-hystrix,feign-hystrix
  cluster-name-expression: metadata['cluster']
  combine-host-port: true
  instanceUrlSuffix:
    ribbon-hystrix: ms-ribbon-hystrix-consumer/actuator/hystrix.stream
    feign-hystrix: ms-feign-hystrix-consumer/actuator/hystrix.stream
